# Discover the cases registered in the zenoh-tests binary and emit a ctest include
# file that registers one ctest case per ztest TEST(...).
#
# Run in script mode (cmake -P) from a custom command that depends on the test target,
# since the case list only exists once the binary has been linked. `zenoh-tests --list`
# prints one "<suite>::<name>" id per line; each becomes an `add_test` invoking the
# binary with `--run <id>`, labeled with its suite so `ctest -L test_broker` selects a
# source file's worth of tests.
#
# Inputs: TEST_EXECUTABLE (the built binary), OUTPUT_FILE (the file to generate).

if(NOT DEFINED TEST_EXECUTABLE OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "ZTestDiscover.cmake requires -D TEST_EXECUTABLE and -D OUTPUT_FILE")
endif()

# Under a coverage build the binary writes a profile on every exit; park this one on a
# fixed path inside the build tree so it neither lands in the working directory nor
# joins the cov-*.profraw set that scripts/coverage.sh merges.
set(ENV{LLVM_PROFILE_FILE} "${OUTPUT_FILE}.profraw")

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list
    OUTPUT_VARIABLE listing
    ERROR_VARIABLE errors
    RESULT_VARIABLE status
    OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "'${TEST_EXECUTABLE} --list' failed (${status}): ${errors}")
endif()

# Test names may contain ';' (a CMake list separator), so escape those before splitting
# the listing on newlines -- otherwise one name would split into two cases.
string(REPLACE ";" "\;" listing "${listing}")
string(REPLACE "\n" ";" lines "${listing}")

set(content "# Generated by tests/ZTestDiscover.cmake -- do not edit.\n")
set(count 0)
foreach(line IN LISTS lines)
    if(line STREQUAL "")
        continue()
    endif()
    # Quote-safe form of the id for the generated file: backslash, double quote and '$'
    # would otherwise be re-interpreted when ctest parses it.
    string(REPLACE "\\" "\\\\" id "${line}")
    string(REPLACE "\"" "\\\"" id "${id}")
    string(REPLACE "$" "\\$" id "${id}")

    string(FIND "${id}" "::" sep)
    if(sep GREATER 0)
        string(SUBSTRING "${id}" 0 ${sep} suite)
    else()
        set(suite "zenoh-tests")
    endif()

    # ctest parses this file with its own reduced interpreter at run time, which only
    # understands the positional add_test(<name> <command> [args...]) signature -- the
    # NAME/COMMAND keyword form silently registers a test literally called "NAME".
    string(APPEND content
        "add_test(\"${id}\" \"${TEST_EXECUTABLE}\" --run \"${id}\")\n"
        "set_tests_properties(\"${id}\" PROPERTIES LABELS \"${suite}\")\n")
    math(EXPR count "${count} + 1")
endforeach()

if(count EQUAL 0)
    message(FATAL_ERROR "'${TEST_EXECUTABLE} --list' produced no test cases")
endif()

# Always write, even when unchanged: the build tracks this file by timestamp, and a
# skipped write would make it look stale and re-run discovery on every build.
file(WRITE "${OUTPUT_FILE}" "${content}")
message(STATUS "Discovered ${count} ztest cases")
